### PR TITLE
Add architecture option

### PR DESCRIPTION
**Pull request by RblSb**
Please add Windows support to Exporter by yourself.

### CODE REVIEW

**Comment by RobDangerous** [comment]
Isn't there some way to do this without putting the architecture in the gradle file? Because there should be, Android Studio manages to do that somehow.

**Comment by RblSb** [comment]
Not sure. This change is for same reason as in #28, `--compile` is broken / too slow for now.
@Disar maybe you know, can gradle set `abiFilters` device-based automatically as Android Studio do? Or maybe we can detect it with adb or something. But it's doesn't solve emulator arch detection and simple compilation without connected device (Android Studio fucked up too).
We also can remove that filter without implicit `--arch` option, but it will be annoying for simple `--compile` usage. And i think it's okay to merge, because almost every android device is arm7 today.

**Comment by RblSb** [comment]
Another solution - remerge #28. What will be wrong if we return other build variants for poor --compile-mans?

**Comment by Disar** [comment]
I've only used gradle as is. I just check the task list and build from there. Calling gradle for the first time sets up a few dependencies for the project, not sure what it does. I always get the `assembleReleaseArm7` and `assembleDebugArm7` build tasks. I haven't done anything with abifilters.

**Comment by RblSb** [comment]
`assembleReleaseArm7` is based on removed releaseArm7 buildType? Because you cannot use it with latest Kha in this case.

**Comment by RobDangerous** [comment]
#28 messes up the build variant list in current Android Studio but we talked about that before. As a general rule of thumb I'll stay as close as possible to what the native IDE creates for each platform unless there's a very good reason not to do so. Looks like I'll have to figure this one out myself.

**Comment by RblSb** [comment]
The reason is that compilation time in android studio will be 7 times slower without connected device in right time (for arm7 arch detection in 98% times). I don't think we can found another solution. If you don't like build variants - lets add that filter with implicit --arch argument? It will save current behaviour with compilation time trap, but it will be possible to fix it, without change build.gradle every project generation.

**Comment by RobDangerous** [comment]
I'm pretty sure it can be fixed, we just need to replicate whatever Android Studio does. Can meanwhile merge the explicit version to do it though.

**Pull request merged**
